### ISSUE TITLE
Tips for Ansible Playbook Development

### ISSUE THREAD

**Issue by heathdbrown** [heathdbrown/research#9]
# Read an article that covered some items on performing debugging tasks in Ansible.
> https://zwischenzugs.com/2021/08/27/five-ansible-techniques-i-wish-id-known-earlier/amp/

1. Use --step to get to a task faster
2. Use inline logging in playbooks for variables
3. Use ansible-console for interacting with modules
4. Use ansible-lint to review playbooks
5. Interact with the ansible debugger on failure and python

**Comment by heathdbrown** [comment]
When testing out the ansible-console I ran into the following issues:

- When running ansible-core 2.11.4 and ansible 4.44 missing import statements for
    - readline - solved by: pipenv install pyreadline " No module named 'readline'"
    - keysm - unsolved: 
      ```
      Traceback (most recent call last):
           File "/home/BrownHD/.local/share/virtualenvs/thousandeyes-agent-config-O4qroPUg/bin/ansible-console", line 104, in <module>
           mycli = getattr(__import__("ansible.cli.%s" % sub, fromlist=[myclass]), myclass)
           File "/home/BrownHD/.local/share/virtualenvs/thousandeyes-agent-config-O4qroPUg/lib/python3.8/site-packages/ansible/cli/console.py", line 12, in <module>
           import readline
           File "/home/BrownHD/.local/share/virtualenvs/thousandeyes-agent-config-O4qroPUg/lib/python3.8/site-packages/readline.py", line 6, in <module>
          from pyreadline.rlmain import Readline
          File "/home/BrownHD/.local/share/virtualenvs/thousandeyes-agent-config-O4qroPUg/lib/python3.8/site-packages/pyreadline/__init__.py", line 12, in <module>
         from . import logger, clipboard, lineeditor, modes, console
        File "/home/BrownHD/.local/share/virtualenvs/thousandeyes-agent-config-O4qroPUg/lib/python3.8/site-packages/pyreadline/clipboard/__init__.py", line 13, in <module>
       from .win32_clipboard import GetClipboardText, SetClipboardText
       File "/home/BrownHD/.local/share/virtualenvs/thousandeyes-agent-config-O4qroPUg/lib/python3.8/site-packages/pyreadline/clipboard/win32_clipboard.py", line 39, in <module>
      from pyreadline.keysyms.winconstants import CF_UNICODETEXT, GHND
      File "/home/BrownHD/.local/share/virtualenvs/thousandeyes-agent-config-O4qroPUg/lib/python3.8/site-packages/pyreadline/keysyms/__init__.py", line 23, in <module>
        raise ImportError("Could not import keysym for local pythonversion", x)
       NameError: name 'x' is not defined
      ```


```
$pip list | grep ansible
ansible      4.4.0
ansible-core 2.11.4

$python --version
Python 3.8.10
```
